services:
  postgresql:
    image: postgres:11.19-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: searchneu_dev,searchneu_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default_password
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  web:
    build: ../../
    depends_on:
      - es
      - postgresql
    ports:
      - 4000:4000
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:default_password@postgresql:5432/searchneu_dev
      POSTGRES_PASSWORD: default_password
      elasticURL: http://es:9200
      TWILIO_PHONE_NUMBER:
      TWILIO_ACCOUNT_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_VERIFY_SERVICE_ID:
      CLIENT_ORIGIN: http://localhost:5000
      JWT_SECRET:
      SLACK_WEBHOOK_URL:

volumes:
  pg:
