version: "2"

services:
  postgresql:
    image: postgres:11.5
    ports:
      - 5432:5432
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=searchneu_dev,searchneu_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  web:
    build: ../../
    depends_on:
      - es
      - postgresql
    command: yarn prod
    ports:
      - 4000:4000
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres@postgresql:5432/searchneu_dev
      elasticURL: http://es:9200
      TWILIO_PHONE_NUMBER:
      TWILIO_ACCOUNT_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_VERIFY_SERVICE_ID:
      CLIENT_ORIGIN: http://localhost:5000
      JWT_SECRET:
      SLACK_WEBHOOK_URL:
volumes:
  pg:
