const elasticProfSerializer = [
  {
    id: "e.adako@northeastern.edu",
    name: "Manny Adako",
    firstName: "Manny",
    lastName: "Adako",
    primaryDepartment: "Men's Basketball",
    primaryRole: "Asst Coach - Men's Basketball",
    phone: null,
    email: "e.adako@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "a.adams@northeastern.edu",
    name: "Alina Adams",
    firstName: "Alina",
    lastName: "Adams",
    primaryDepartment: "DMSB Office of the Dean",
    primaryRole: "Part-Time Lecturer",
    phone: "4082292292",
    email: "a.adams@northeastern.edu",
    officeRoom: "6024 Silver Creek Road, San Jose, CA, 95138",
  },
  {
    id: "as.adams@northeastern.edu",
    name: "Ashley Adams",
    firstName: "Ashley",
    lastName: "Adams",
    primaryDepartment: "Mills College",
    primaryRole: "Associate Adjunct Professor",
    phone: "5104302082",
    email: "as.adams@northeastern.edu",
    officeRoom: "5000 MacArthur Blvd, Oakland, CA, 94613",
  },
  {
    id: "da.adams@northeastern.edu",
    name: "Daniel Adams",
    firstName: "Daniel",
    lastName: "Adams",
    primaryDepartment: "Architecture",
    primaryRole: "Assoc Professor & Director",
    phone: "6173734637",
    email: "da.adams@northeastern.edu",
    officeRoom: "151 RY, Boston, MA, 02115",
  },
  {
    id: "jan.adams@northeastern.edu",
    name: "Jane Adams",
    firstName: "Jane",
    lastName: "Adams",
    primaryDepartment: "School Of Nursing",
    primaryRole: "Part-Time Lecturer",
    phone: "6173733649",
    email: "jan.adams@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "l.adams@northeastern.edu",
    name: "Leslie Adams",
    firstName: "Leslie",
    lastName: "Adams",
    primaryDepartment: "School Of Nursing",
    primaryRole: "Part-Time Lecturer",
    phone: null,
    email: "l.adams@northeastern.edu",
    officeRoom: "103 RB, Boston, MA, 02115",
  },
  {
    id: "ma.adams@northeastern.edu",
    name: "Marie Adams",
    firstName: "Marie",
    lastName: "Adams",
    primaryDepartment: "Architecture",
    primaryRole: "Associate Professor",
    phone: null,
    email: "ma.adams@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "n.adams@northeastern.edu",
    name: "Nikole Adams",
    firstName: "Nikole",
    lastName: "Adams",
    primaryDepartment: "Oakland University Advancement",
    primaryRole: "Associate VP for Advancement",
    phone: "5104302229",
    email: "n.adams@northeastern.edu",
    officeRoom: "5000 MacArthur Blvd, Oakland, CA, 94613",
  },
  {
    id: "s.adams@northeastern.edu",
    name: "Stephanie Adams",
    firstName: "Stephanie",
    lastName: "Adams",
    primaryDepartment: "DMSB-Graduate",
    primaryRole: "Academic Advisor",
    phone: null,
    email: "s.adams@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "m.adams@northeastern.edu",
    name: "Marybeth Adams-Khoury",
    firstName: "Marybeth",
    lastName: "Adams-Khoury",
    primaryDepartment: "BCHS Office of the Dean",
    primaryRole: "Part-Time Lecturer",
    phone: null,
    email: "m.adams@northeastern.edu",
    officeRoom: "102 RB, Boston, MA, 02120",
  },
  {
    id: "t.addaquay@northeastern.edu",
    name: "Kojo Addaquay",
    firstName: "Kojo",
    lastName: "Addaquay",
    primaryDepartment: "Internal Consulting",
    primaryRole: "Finance Business Systems Analyst",
    phone: null,
    email: "t.addaquay@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "q.addison@northeastern.edu",
    name: "Quisquella Addison",
    firstName: "Quisquella",
    lastName: "Addison",
    primaryDepartment: "School Of Law-Academic",
    primaryRole: "Assistant Teaching Professor",
    phone: null,
    email: "q.addison@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "m.addorisio@northeastern.edu",
    name: "Michael Addorisio",
    firstName: "Michael",
    lastName: "Addorisio",
    primaryDepartment: "Engineering-Computer Center",
    primaryRole: "Financial Aid Assistant",
    phone: null,
    email: "m.addorisio@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "o.adekoya@northeastern.edu",
    name: "Olugbenga Adekoya",
    firstName: "Olugbenga",
    lastName: "Adekoya",
    primaryDepartment: "College of Professional Studies",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "o.adekoya@northeastern.edu",
    officeRoom: "100 Fore Street, Portland, ME, 04101",
  },
  {
    id: "k.aden@northeastern.edu",
    name: "Kenan Aden",
    firstName: "Kenan",
    lastName: "Aden",
    primaryDepartment: "Seattle Regional Campus",
    primaryRole: "Operations Coordinator",
    phone: null,
    email: "k.aden@northeastern.edu",
    officeRoom: "401 Terry Ave N, Suite 103, Seattle, WA, 98109",
  },
  {
    id: "2f96a14f-1559-42e5-a9de-24e0bca356cc",
    name: "Yahia Adla",
    firstName: "Yahia",
    lastName: "Adla",
    primaryDepartment: "Pharmaceutical Sciences",
    primaryRole: null,
    phone: null,
    email: null,
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "l.adler@northeastern.edu",
    name: "Libby Adler",
    firstName: "Libby",
    lastName: "Adler",
    primaryDepartment: "School Of Law-Academic",
    primaryRole: "Professor",
    phone: "6173737513",
    email: "l.adler@northeastern.edu",
    officeRoom: "120 KN, Boston, MA, 02115",
  },
  {
    id: "g.adomdza@northeastern.edu",
    name: "Gordon Adomdza",
    firstName: "Gordon",
    lastName: "Adomdza",
    primaryDepartment: "DMSB Office of the Dean",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "g.adomdza@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "l.adrien@northeastern.edu",
    name: "Laura Adrien",
    firstName: "Laura",
    lastName: "Adrien",
    primaryDepartment: "Khoury-Graduate",
    primaryRole: "Asst Dir - Graduate Student Services",
    phone: "6173737112",
    email: "l.adrien@northeastern.edu",
    officeRoom: "502 Dana Research Center, Boston, MA, 02115",
  },
  {
    id: "n.aduama@northeastern.edu",
    name: "Nicolette Aduama",
    firstName: "Nicolette",
    lastName: "Aduama",
    primaryDepartment: "Center for the Study of Sport In So",
    primaryRole: "Sr Assoc Dir - Sports in Society",
    phone: "6173737445",
    email: "n.aduama@northeastern.edu",
    officeRoom: "41 BV, Boston, MA, 02115",
  },
  {
    id: "v.aduri@northeastern.edu",
    name: "Srujana Aduri",
    firstName: "Srujana",
    lastName: "Aduri",
    primaryDepartment: "ITS Enterprise Application Dev",
    primaryRole: "Database Administrator",
    phone: null,
    email: "v.aduri@northeastern.edu",
    officeRoom: "216, Boston, MA, 02115",
  },
  {
    id: "w.aerts@northeastern.edu",
    name: "Bill Aerts",
    firstName: "Bill",
    lastName: "Aerts",
    primaryDepartment: "Electrical and Computer Engineering",
    primaryRole: "Managing Dir",
    phone: null,
    email: "w.aerts@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "l.afrookteh@northeastern.edu",
    name: "Lane Afrookteh",
    firstName: "Lane",
    lastName: "Afrookteh",
    primaryDepartment: "CAMD-Office of the Dean",
    primaryRole: "Graduate Programs Coordinator",
    phone: null,
    email: "l.afrookteh@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "j.agar@northeastern.edu",
    name: "Jeffrey Agar",
    firstName: "Jeffrey",
    lastName: "Agar",
    primaryDepartment: "Chemistry and Chemical Biology",
    primaryRole: "Associate Professor",
    phone: "6173735909",
    email: "j.agar@northeastern.edu",
    officeRoom: "412 TF, Boston, MA, 02111",
  },
  {
    id: "as.agarwal@northeastern.edu",
    name: "Ashna Agarwal",
    firstName: "Ashna",
    lastName: "Agarwal",
    primaryDepartment: "Bay Area Regional Campuses",
    primaryRole: "Administrative Assistant - Dean's Office",
    phone: null,
    email: "as.agarwal@northeastern.edu",
    officeRoom: "4 N 2nd St, Suite 300, San Jose, CA, 95113",
  },
  {
    id: "g.agganis@northeastern.edu",
    name: "Georgia Agganis",
    firstName: "Georgia",
    lastName: "Agganis",
    primaryDepartment: "School Of Nursing",
    primaryRole: "Part-Time Lecturer",
    phone: "6173733649",
    email: "g.agganis@northeastern.edu",
    officeRoom: "102 RB, Boston, MA, 02111",
  },
  {
    id: "k.aggarwal@northeastern.edu",
    name: "Kartik Aggarwal",
    firstName: "Kartik",
    lastName: "Aggarwal",
    primaryDepartment: "Roux Institute",
    primaryRole: "Geospatial-Temporal Data Scientist",
    phone: null,
    email: "k.aggarwal@northeastern.edu",
    officeRoom: "100 Fore Street, Portland, ME, 04101",
  },
  {
    id: "n.aggarwal@northeastern.edu",
    name: "Neha Aggarwal",
    firstName: "Neha",
    lastName: "Aggarwal",
    primaryDepartment: "Marketing Group",
    primaryRole: null,
    phone: null,
    email: "n.aggarwal@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "r.aggarwal@northeastern.edu",
    name: "Rajesh Aggarwal",
    firstName: "Rajesh",
    lastName: "Aggarwal",
    primaryDepartment: "DMSB Finance Group",
    primaryRole: "Professor",
    phone: "6173738333",
    email: "r.aggarwal@northeastern.edu",
    officeRoom: "413 HA, Boston, MA, 02115",
  },
  {
    id: "s.aghababaei@northeastern.edu",
    name: "Bahar Aghababaei",
    firstName: "Bahar",
    lastName: "Aghababaei",
    primaryDepartment: "College of Professional Studies",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "s.aghababaei@northeastern.edu",
    officeRoom:
      "First Canadian Place, 100 King St. West, Suite 4620, Toronto, ON, M5X 1E2",
  },
  {
    id: "m.aghahowa@northeastern.edu",
    name: "Michael Aghahowa",
    firstName: "Michael",
    lastName: "Aghahowa",
    primaryDepartment: "Art + Design",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "m.aghahowa@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "a.agostinelli@northeastern.edu",
    name: "Adam Agostinelli",
    firstName: "Adam",
    lastName: "Agostinelli",
    primaryDepartment: "College of Professional Studies",
    primaryRole: "Academic Advisor",
    phone: null,
    email: "a.agostinelli@northeastern.edu",
    officeRoom: "50 NI, Boston, MA, 02111",
  },
  {
    id: "c.agostinelli-fucile@northeastern.edu",
    name: "Christina Agostinelli-Fucile",
    firstName: "Christina",
    lastName: "Agostinelli-Fucile",
    primaryDepartment: "World Language Center",
    primaryRole: "Assoc Teaching Professor",
    phone: null,
    email: "c.agostinelli-fucile@northeastern.edu",
    officeRoom: "400 ME, Boston, MA, 02115",
  },
  {
    id: "g.agostoroman@northeastern.edu",
    name: "Genesis Agosto Roman",
    firstName: "Genesis",
    lastName: "Agosto Roman",
    primaryDepartment: "Civil and Environmental Engineering",
    primaryRole: "Study Nurse",
    phone: null,
    email: "g.agostoroman@northeastern.edu",
    officeRoom: "360 Huntington Ave, Boston, MA, 02115",
  },
  {
    id: "j.agress@northeastern.edu",
    name: "Jason Agress",
    firstName: "Jason",
    lastName: "Agress",
    primaryDepartment: "CPS-Undergraduate Programs",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "j.agress@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "e.aguayo@northeastern.edu",
    name: "Ethel Aguayo",
    firstName: "Ethel",
    lastName: "Aguayo",
    primaryDepartment: "Accounts Payable",
    primaryRole: "Accounts Payable Clerk",
    phone: "5104302121",
    email: "e.aguayo@northeastern.edu",
    officeRoom: "5000 MacArthur Blvd, Oakland, CA, 94613",
  },
  {
    id: "a.aguiar@northeastern.edu",
    name: "Aniella Aguiar",
    firstName: "Aniella",
    lastName: "Aguiar",
    primaryDepartment: "Oakland Library",
    primaryRole: "Donor Engagement & Adv Svc Assistant",
    phone: null,
    email: "a.aguiar@northeastern.edu",
    officeRoom: "5000 MacArthur Blvd, Oakland, CA, 94613",
  },
  {
    id: "b.aguiar@northeastern.edu",
    name: "Brian Aguiar",
    firstName: "Brian",
    lastName: "Aguiar",
    primaryDepartment: "PREF (Planning Real Estate & Facil)",
    primaryRole: "Project Manager",
    phone: null,
    email: "b.aguiar@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "e.aguiar@northeastern.edu",
    name: "Everaldo Aguiar",
    firstName: "Everaldo",
    lastName: "Aguiar",
    primaryDepartment: "Graduate Campus-Seattle Khoury",
    primaryRole: "Part-Time Lecturer",
    phone: "2064675480",
    email: "e.aguiar@northeastern.edu",
    officeRoom: "109 SEA, Seattle, WA, 98109",
  },
  {
    id: "k.aguiar@northeastern.edu",
    name: "Kenneth Aguiar",
    firstName: "Kenneth",
    lastName: "Aguiar",
    primaryDepartment: "College of Professional Studies",
    primaryRole: "Lecturer",
    phone: null,
    email: "k.aguiar@northeastern.edu",
    officeRoom: "41 BV, Boston, MA, 02111",
  },
  {
    id: "r.aguilera@northeastern.edu",
    name: "Ruth Aguilera",
    firstName: "Ruth",
    lastName: "Aguilera",
    primaryDepartment: "International Business and Strategy",
    primaryRole: "Professor",
    phone: "6173734639",
    email: "r.aguilera@northeastern.edu",
    officeRoom: "304 HA, Boston, MA, 02111",
  },
  {
    id: "e.aguirre@northeastern.edu",
    name: "Eddie Aguirre",
    firstName: "Eddie",
    lastName: "Aguirre",
    primaryDepartment: "ITS-Office of Information Security",
    primaryRole: "Systems Administrator",
    phone: null,
    email: "e.aguirre@northeastern.edu",
    officeRoom: "302 216, Boston, MA, 02115",
  },
  {
    id: "a.agustin@northeastern.edu",
    name: "Allyson Agustin",
    firstName: "Allyson",
    lastName: "Agustin",
    primaryDepartment: "Enrollment Management",
    primaryRole: "Associate Enrollment Management TeleHuskies & Ambassadors",
    phone: null,
    email: "a.agustin@northeastern.edu",
    officeRoom: "370 Common Street, Dedham, MA, 02026",
  },
  {
    id: "r.aguy@northeastern.edu",
    name: "Rashnide Aguy",
    firstName: "Rashnide",
    lastName: "Aguy",
    primaryDepartment: "CAMD-Undergraduate Advising",
    primaryRole: "Academic Advisor",
    phone: null,
    email: "r.aguy@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "k.ahkee@northeastern.edu",
    name: "Isabel Ah Kee",
    firstName: "Isabel",
    lastName: "Ah Kee",
    primaryDepartment: "Audit & Advisory Services",
    primaryRole: "Dir - Audit",
    phone: "6173737745",
    email: "k.ahkee@northeastern.edu",
    officeRoom: "101 BV, Boston, MA, 02115",
  },
  {
    id: "j.ahearn@northeastern.edu",
    name: "Jeneva Ahearn",
    firstName: "Jeneva",
    lastName: "Ahearn",
    primaryDepartment: "Pharm & Hlth Systems Sciences",
    primaryRole: "Postdoctoral Research Fellow",
    phone: null,
    email: "j.ahearn@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "j.ahearne@northeastern.edu",
    name: "Jim Ahearne",
    firstName: "Jim",
    lastName: "Ahearne",
    primaryDepartment: "Roux Institute",
    primaryRole: "Assoc Dir - Partnerships",
    phone: null,
    email: "j.ahearne@northeastern.edu",
    officeRoom: "100 Fore Street, Portland, ME, 04101",
  },
  {
    id: "f.ahern@northeastern.edu",
    name: "Daniel Ahern Jr",
    firstName: "Daniel",
    lastName: "Ahern Jr",
    primaryDepartment: "Political Science",
    primaryRole: "Part-Time Lecturer",
    phone: "6173733796",
    email: "f.ahern@northeastern.edu",
    officeRoom: "303 ME, Boston, MA, 02115",
  },
  {
    id: "me.ahern@northeastern.edu",
    name: "Meghan Ahern",
    firstName: "Meghan",
    lastName: "Ahern",
    primaryDepartment: "Applied Psychology",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "me.ahern@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "m.ahern@northeastern.edu",
    name: "Michael Ahern",
    firstName: "Michael",
    lastName: "Ahern",
    primaryDepartment: "COE-Departmental Co-op",
    primaryRole: "Associate Coop Coordinator",
    phone: "6173735578",
    email: "m.ahern@northeastern.edu",
    officeRoom: "344 HO, Boston, MA, 02111",
  },
  {
    id: "i.ahmad@northeastern.edu",
    name: "Ibrahim Said Ahmad",
    firstName: "Ibrahim Said",
    lastName: "Ahmad",
    primaryDepartment: "Office Of The Provost",
    primaryRole: "Postdoctoral Research Fellow",
    phone: null,
    email: "i.ahmad@northeastern.edu",
    officeRoom: "100 Fore Street, Portland, ME, 04101",
  },
  {
    id: "u.ahmad@northeastern.edu",
    name: "Uzair Ahmad",
    firstName: "Uzair",
    lastName: "Ahmad",
    primaryDepartment: "Khoury",
    primaryRole: "Part-Time Lecturer",
    phone: null,
    email: "u.ahmad@northeastern.edu",
    officeRoom: "360 Huntington Ave, Boston, MA, 02115",
  },
  {
    id: "f.ahmadiabkenari@northeastern.edu",
    name: "Fatemeh Ahmadi Abkenari",
    firstName: "Fatemeh",
    lastName: "Ahmadi Abkenari",
    primaryDepartment: "Graduate Campus-Vancouver CPS",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "f.ahmadiabkenari@northeastern.edu",
    officeRoom: "410 West Georgia St, Suite 1400, Vancouver, BC, V6B 1Z3",
  },
  {
    id: "b.ahmadi@northeastern.edu",
    name: "Behzad Ahmadi",
    firstName: "Behzad",
    lastName: "Ahmadi",
    primaryDepartment: "College of Professional Studies",
    primaryRole: "Lecturer",
    phone: null,
    email: "b.ahmadi@northeastern.edu",
    officeRoom: "Street Not Available, ",
  },
  {
    id: "e.ahmadi@northeastern.edu",
    name: "ELHAM AHMADI",
    firstName: "ELHAM",
    lastName: "AHMADI",
    primaryDepartment: "Graduate Campus-Toronto CPS",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "e.ahmadi@northeastern.edu",
    officeRoom:
      "First Canadian Place, 100 King St. West, Suite 4620, Toronto, ON, M5X 1E2",
  },
];

export default elasticProfSerializer;
