const elasticCourseFixtures = [
  {
    classAttributes: ["Engineering  UBEN"],
    classId: "3410",
    coreqs: { type: "and", values: [] },
    description:
      "Covers advanced analog and mixed-signal circuit analysis topics. Introduces analog integrated circuits (ICs) concepts with bipolar and field effect transistor devices. Covered IC building blocks include current sources and active loads, differential stages, cascode configurations, gain stages, and output stages. The uses of the building blocks are demonstrated for the design of popular ICs, such as operational amplifiers and voltage comparators. The high-frequency circuit models of transistors are described and used to evaluate the frequency responses of amplifiers. Introduces analog-to-digital and digital-to-analog conversion concepts and the concepts of feedback and instability with applications to the design of amplifiers and oscillators. The course makes extensive use of the SPICE simulation tool for assignments and projects.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/EECE/3410",
    lastUpdateTime: new Date("2024-10-16T22:34:45.127Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Electronic Design",
    nupath: [],
    optPrereqsFor: [{ classId: "5649", subject: "EECE" }],
    prereqs: { type: "and", values: [{ classId: "2412", subject: "EECE" }] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=EECE&crse_numb_in=3410",
    subject: "EECE",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=EECE&crse_in=3410&schd_in=%",
  },
  {
    classAttributes: ["GS Col of Arts, Media & Design  GBAM"],
    classId: "6600",
    coreqs: { type: "and", values: [] },
    description:
      "Offers students an opportunity to learn a human-centered design perspective and to develop experience design competency in the complex context of interpersonal and group interactions. Experience design is a holistic approach that investigates the human experience in specific situations in order to improve its quality. Students study the person-to-person aspect of human-centered design through readings and in-class activities, as well as practice applying its perspectives, models, and theories to the project process. Students are asked to participate in class discussions and create compelling experience design projects to address the needs, desires, fears, and aspirations of their audience.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/ARTG/6600",
    lastUpdateTime: new Date("2024-10-16T22:34:12.886Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Experience Design Studio 2: Group and Interpersonal",
    nupath: [],
    optPrereqsFor: [{ classId: "6700", subject: "ARTG" }],
    prereqs: { type: "and", values: [{ classId: "5600", subject: "ARTG" }] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=ARTG&crse_numb_in=6600",
    subject: "ARTG",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=ARTG&crse_in=6600&schd_in=%",
  },
  {
    classAttributes: ["GSEN Engineering  GBEN"],
    classId: "6400",
    coreqs: { type: "and", values: [] },
    description:
      "Offers topics and skills designed to prepare students for advanced courses in data analytics engineering. Covers basic concepts and implementation of methods related to probability, eigenvalues and eigenvectors, cluster analysis, text mining, and time series analysis. Offers students an opportunity to learn how to work with modern data structures and apply computational methods for data cleaning and data wrangling operations.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202350/IE/6400",
    lastUpdateTime: new Date("2024-10-16T22:34:12.886Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Foundations Data Analytics Eng",
    nupath: [],
    optPrereqsFor: [{ classId: "7275", subject: "IE" }],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202350&subj_code_in=IE&crse_numb_in=6400",
    subject: "IE",
    termId: "202350",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202350&subj_in=IE&crse_in=6400&schd_in=%",
  },
  {
    classAttributes: ["GSEN Engineering  GBEN"],
    classId: "7275",
    coreqs: { type: "and", values: [] },
    description:
      "Offers a fundamental course in fluid dynamics designed to prepare the student for more advanced courses in the thermofluids curriculum while providing a strong background in fluid mechanics. Topics include Cartesian tensors; differential and integral formulation of the equations of conservation of mass, momentum, and energy; molecular and continuum transport phenomena; the Navier-Stokes equations; vorticity; inviscid incompressible flow, the velocity potential, and Bernoulli‘s equation; viscous incompressible flow; the stream function; some exact solutions; energy equation including heat conduction and viscous dissipation, low Reynolds number flow, exact and approximate approaches to laminar boundary layers in high Reynolds number flows, stability of laminar flows and the transition to turbulence, and treatment of incompressible turbulent mean flow; and internal and external flows.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/ME/7275",
    lastUpdateTime: new Date("2024-10-16T22:34:12.886Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Essentials of Fluid Dynamics",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [{ classId: "6200", subject: "ME" }] },
    prereqsFor: [{ classId: "7310", subject: "ME" }],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=ME&crse_numb_in=7275",
    subject: "ME",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=ME&crse_in=7275&schd_in=%",
  },
  {
    classAttributes: [
      "NUpath Creative Express/Innov  NCEI",
      "UG Col of Arts, Media & Design  UBAM",
    ],
    classId: "2101",
    coreqs: { type: "and", values: [] },
    description:
      "Offers students an opportunity to learn the necessary techniques to utilize current Musical Instrument Digital Interface (MIDI) and audio technology in the production of professional-quality song demos, including intermediate to advanced skills and concepts of MIDI, synthesis, multitrack recording, mixing, and sound processing. Covers musical approaches to the effective assembly and arranging of sound materials using professional digital audio workstations (DAWs). Focuses on techniques to import and export both MIDI and audio data to greater facilitate collaboration within the virtual classroom as well as using external collaborators (across a variety of DAWs and platforms). Songwriting skills are also critiqued.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/MUSI/2101",
    lastUpdateTime: new Date("2024-10-16T22:34:45.127Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Demo Production for Songwriters",
    nupath: ["Creative Express/Innov"],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=MUSI&crse_numb_in=2101",
    subject: "MUSI",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=MUSI&crse_in=2101&schd_in=%",
  },
  {
    classAttributes: ["Bouve Health Sci  UBBV"],
    classId: "2000",
    coreqs: { type: "and", values: [] },
    description:
      "Introduces the Bouvé Cooperative Education Program. Offers students an opportunity to develop job-search and career-management skills. Students perform assessments of their workplace skills, interests, and values and discuss how they impact personal career decisions. Offers students an opportunity to prepare a professional-style résumé, learn proper interviewing techniques, and gain an understanding of the opportunities available to them for co-op. Introduces career paths, choices, and career decision making. Familiarizes students with workplace issues relative to their field of study and presents the MyNEU COOL database in the job-search and referral process. Presents and discusses co-op policies, procedures, and expectations of the Bouvé Cooperative Education Program and co-op employers.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/NRSG/2000",
    lastUpdateTime: new Date("2024-10-16T22:34:45.127Z"),
    maxCredits: 1,
    minCredits: 1,
    name: "Professional Development for Co-op",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=NRSG&crse_numb_in=2000",
    subject: "NRSG",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=NRSG&crse_in=2000&schd_in=%",
  },
  {
    classAttributes: ["GSBV Bouve  GBBV"],
    classId: "5226",
    coreqs: { type: "and", values: [] },
    description:
      "Focuses on management challenges facing healthcare organizations, particularly community-based agencies and their role in the public healthcare delivery system. Introduces strategic thinking and leadership approaches that must be considered for managing a successful healthcare organization. Selected topics include strategic planning; organizational development and the barriers to organizational change; relationship management with key internal and external constituencies; marketing, financial management, and contract negotiation; evolving principles of health insurance and the changing role of the consumer; and the key elements for effective organizational leadership in today’s evolving healthcare marketplace. When appropriate, outside experts are used to supplement readings, case studies, and lecture and discuss practical real-world challenges in leading various healthcare initiatives. Requires permission of instructor for students outside designated programs.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/PHTH/5226",
    lastUpdateTime: new Date("2024-10-16T22:34:45.127Z"),
    maxCredits: 3,
    minCredits: 3,
    name: "Strategic Management and Leadership in Healthcare",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=PHTH&crse_numb_in=5226",
    subject: "PHTH",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=PHTH&crse_in=5226&schd_in=%",
  },
  {
    classAttributes: [
      "NU Core Math/Anly Think Lvl 2  NCM2",
      "Engineering  UBEN",
    ],
    classId: "2361",
    coreqs: { type: "and", values: [] },
    description:
      "Covers applications to applied mechanics, thermofluids, and dynamics/control problems relevant to engineering. Topics include differential equations applied to modeling and characterization of processes, linear algebra used for multidimensional and complex system computations and modeling, and statistics and probability used for controls and signal analysis, among other applications. Introduces the foundational basis for approximate methods of engineering analysis, including its application to finite element analysis.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202310/GE/2361",
    lastUpdateTime: new Date("2024-10-16T22:34:12.886Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Mathematical Methods for Engineers",
    nupath: [],
    optPrereqsFor: [
      { classId: "2355", subject: "BIOE" },
      { classId: "3210", subject: "BIOE" },
      { classId: "3310", subject: "BIOE" },
      { classId: "3380", subject: "BIOE" },
      { classId: "5115", subject: "BIOE" },
      { classId: "2520", subject: "EECE" },
      { classId: "4508", subject: "ME" },
      { classId: "4565", subject: "ME" },
    ],
    prereqs: { type: "and", values: [{ classId: "1342", subject: "MATH" }] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202310&subj_code_in=GE&crse_numb_in=2361",
    subject: "GE",
    termId: "202310",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202310&subj_in=GE&crse_in=2361&schd_in=%",
  },
];

export default elasticCourseFixtures;
