const profPartialFixtures = [
  {
    id: "b.brown@northeastern.edu",
    name: "Ben Brown",
    firstName: "Ben",
    lastName: "Brown",
    primaryDepartment: "BCHS Office of the Dean",
    primaryRole: "Assoc Dir - Data Analytics",
    phone: "6173736303",
    email: "b.brown@northeastern.edu",
    officeRoom: "120 BK, Boston, MA, 02115",
  },
  {
    id: "b.caras@northeastern.edu",
    name: "Ben Caras",
    firstName: "Ben",
    lastName: "Caras",
    primaryDepartment: "Art + Design",
    primaryRole: "Assistant Teaching Professor",
    phone: "6173732347",
    email: "b.caras@northeastern.edu",
    officeRoom: "239 RY, Boston, MA, 02115",
  },
  {
    id: "b.carr@northeastern.edu",
    name: "Ben Carr",
    firstName: "Ben",
    lastName: "Carr",
    primaryDepartment: "Graduate Campus-Seattle CPS",
    primaryRole: null,
    phone: null,
    email: "b.carr@northeastern.edu",
    officeRoom: "401 Terry Ave N, Suite 103, Seattle, WA, 98109",
  },
  {
    id: "b.cooley@northeastern.edu",
    name: "Ben Cooley",
    firstName: "Ben",
    lastName: "Cooley",
    primaryDepartment: "Art + Design",
    primaryRole: "Part Time Lecturer",
    phone: null,
    email: "b.cooley@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "b.davaji@northeastern.edu",
    name: "Ben Davaji",
    firstName: "Ben",
    lastName: "Davaji",
    primaryDepartment: "Electrical and Computer Engineering",
    primaryRole: "Assistant Professor",
    phone: null,
    email: "b.davaji@northeastern.edu",
    officeRoom: "DA 428, Boston, MA, 02111",
  },
  {
    id: "b.jeter@northeastern.edu",
    name: "Ben Jeter",
    firstName: "Ben",
    lastName: "Jeter",
    primaryDepartment: "Residence Hall-Programs",
    primaryRole: "Residence Director",
    phone: null,
    email: "b.jeter@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "b.june@northeastern.edu",
    name: "Ben June",
    firstName: "Ben",
    lastName: "June",
    primaryDepartment: "ITS Enterprise Application Dev",
    primaryRole: "Sr Devops Architect",
    phone: "6173738983",
    email: "b.june@northeastern.edu",
    officeRoom: "302-216, Boston, MA, 02115",
  },
  {
    id: "a.lerner@northeastern.edu",
    name: "Ada Lerner",
    firstName: "Ada",
    lastName: "Lerner",
    primaryDepartment: "Khoury",
    primaryRole:
      "Assistant Professor & Director of the BS in Cybersecurity Program",
    phone: null,
    email: "a.lerner@northeastern.edu",
    officeRoom: "360 Huntington Avenue, Boston, MA, 02115",
  },
  {
    id: "be.lerner@northeastern.edu",
    name: "Ben Lerner",
    firstName: "Ben",
    lastName: "Lerner",
    primaryDepartment: "Khoury",
    primaryRole: "Associate Teaching Professor",
    phone: null,
    email: "be.lerner@northeastern.edu",
    officeRoom: "202 WVH, Boston, MA, 02115",
  },
  {
    id: "n.lerner@northeastern.edu",
    name: "Neal Lerner",
    firstName: "Neal",
    lastName: "Lerner",
    primaryDepartment: "English",
    primaryRole: "Professor",
    phone: "6173732451",
    email: "n.lerner@northeastern.edu",
    officeRoom: "405 LA, Boston, MA, 02115",
  },
];

export default profPartialFixtures;
