const hydrateCourseFixtures = [
  {
    classAttributes: [
      "NUpath Creative Express/Innov  NCEI",
      "UG Col of Arts, Media & Design  UBAM",
    ],
    classId: "1250",
    coreqs: { type: "and", values: [] },
    description:
      "Explores common design practices, principles, and vocabularies, introducing the design process as a method of inquiry and problem solving through studio projects. Emphasizes the importance of an awareness of audience and context in the creation of meaningful communications and experiences. Explores the practice of design as an iterative process, offering students an opportunity to obtain an understanding of the value of systems thinking and the importance of feedback and exchange as a means for assessing the quality of design’s effectiveness in helping users achieve their goals.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/ARTG/1250",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Design Process Context and Systems",
    nupath: ["Creative Express/Innov"],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=ARTG&crse_numb_in=1250",
    subject: "ARTG",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=ARTG&crse_in=1250&schd_in=%",
  },
  {
    classAttributes: ["Computer&Info Sci  UBCS"],
    classId: "4360",
    coreqs: { type: "and", values: [] },
    description:
      "Introduces computer graphics algorithms and concepts primarily focusing on offline rendering techniques. Consists of a lecture component and in-class laboratory to study common image synthesis algorithms and techniques to generate images used in games and 3D animated movies. Culminates with a final project in which students complete in groups or individually a renderer for generating high quality images. Students with an interest in a career as a graphics, rendering, or high performance computer engineer may consider taking this course.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/CS/4360",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Non-Interactive Computer Graphics",
    nupath: [],
    optPrereqsFor: [],
    prereqs: {
      type: "and",
      values: [
        {
          type: "or",
          values: [
            { classId: "2810", subject: "CS" },
            { classId: "2331", subject: "MATH" },
          ],
        },
        { classId: "3500", subject: "CS" },
      ],
    },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=CS&crse_numb_in=4360",
    subject: "CS",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=CS&crse_in=4360&schd_in=%",
  },
  {
    classAttributes: ["GSCS Computer & Info Science  GBCS"],
    classId: "5360",
    coreqs: { type: "and", values: [] },
    description:
      "Introduces computer graphics algorithms and concepts. Focuses on offline rendering techniques. Consists of a lecture component and in-class laboratory offering instruction about common image synthesis algorithms and techniques to generate images used in games and 3D-animated movies. Culminates in a final individual or group project to complete a renderer for generating high-quality images. This course is appropriate for students interested in a career as a graphics, rendering, or high-performance computer engineer.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/CS/5360",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Noninteractive Computer Graphics",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=CS&crse_numb_in=5360",
    subject: "CS",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=CS&crse_in=5360&schd_in=%",
  },
  {
    classAttributes: ["Engineering  UBEN"],
    classId: "2322",
    coreqs: { type: "and", values: [{ classId: "2323", subject: "EECE" }] },
    description:
      "Covers the design and evaluation of control and data structures for digital systems. Uses hardware description languages to describe and design both behavioral and register-transfer-level architectures and control units. Topics covered include number systems, data representation, a review of combinational and sequential digital logic, finite state machines, arithmetic-logic unit (ALU) design, basic computer architecture, the concepts of memory and memory addressing, digital interfacing, timing, and synchronization. Assignments include designing and simulating digital hardware models using Verilog as well as some assembly language to expose the interface between hardware and software.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/EECE/2322",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Fundamentals of Digital Design and Computer Organization",
    nupath: [],
    optPrereqsFor: [{ classId: "4790", subject: "EECE" }],
    prereqs: {
      type: "or",
      values: [
        { classId: "2160", subject: "EECE" },
        {
          type: "and",
          values: [
            { classId: "1800", subject: "CS" },
            { classId: "2510", subject: "CS" },
          ],
        },
      ],
    },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=EECE&crse_numb_in=2322",
    subject: "EECE",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=EECE&crse_in=2322&schd_in=%",
  },
  {
    classAttributes: [
      "NU Core Capstone  NCC1",
      "NUpath Capstone Experience  NCCE",
      "NU Core Experiential Learning  NCE1",
      "NUpath Creative Express/Innov  NCEI",
      "NU Core Writing Intsv in Majr  NCW2",
      "NUpath Writing Intensive  NCWI",
      "Engineering  UBEN",
    ],
    classId: "4790",
    coreqs: { type: "and", values: [] },
    description:
      "Requires students to select a project requiring design and implementation of an electrical, electronic, and/or software system, including evaluation of multiple constraints and use of appropriate engineering standards in the design; formation of a team to carry out the project; and submission and presentation of a detailed proposal for the work. Students must specify the materials needed for their project, provide a cost analysis, and make arrangements with their capstone adviser to purchase and/or secure donation of equipment. Requires students to perform a feasibility study by extensive simulation or prototype design of subsystems to facilitate the second phase of the capstone design, considering public health, safety and welfare, global, cultural, social, environmental, and economic factors.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/EECE/4790",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Electrical and Computer Engineering Capstone 1",
    nupath: [
      "Capstone Experience",
      "Creative Express/Innov",
      "Writing Intensive",
    ],
    optPrereqsFor: [],
    prereqs: {
      type: "or",
      values: [
        { classId: "2322", subject: "EECE" },
        { classId: "2412", subject: "EECE" },
        { classId: "2520", subject: "EECE" },
        { classId: "2530", subject: "EECE" },
        { classId: "2540", subject: "EECE" },
        { classId: "2560", subject: "EECE" },
        { classId: "3000", subject: "CS" },
      ],
    },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=EECE&crse_numb_in=4790",
    subject: "EECE",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=EECE&crse_in=4790&schd_in=%",
  },
  {
    classAttributes: ["GSBV Health Informatics Online  GBHI"],
    classId: "5101",
    coreqs: { type: "and", values: [] },
    description:
      "Introduces the history and current status of information systems in healthcare: information architectures, administrative and clinical applications, evidence-based medicine, information retrieval, decision support systems, security and confidentiality, bioinformatics, information system cycles, the electronic health record, key health information systems and standards, and medical devices. Requires enrollment in Graduate Health Informatics Program.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/HINF/5101",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 3,
    minCredits: 3,
    name: "Introduction to Health Informatics and Health Information Systems",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=HINF&crse_numb_in=5101",
    subject: "HINF",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=HINF&crse_in=5101&schd_in=%",
  },
  {
    classAttributes: ["GSEN Information Systems  GBIN"],
    classId: "7225",
    coreqs: { type: "and", values: [] },
    description:
      "Covers the latest engineering principles necessary for building complex software systems that comply with recognized standards in the financial industry. With automated business processes today, risk and responsibility are shifting to information technology (IT) systems. Offers students an opportunity to learn how to incorporate information-based controls related to the financial industry that signal trouble, detect violations, and provide accountability, as well as a working approval process. Emphasizes software design. Seeks to help engineers construct complex software from a sophisticated engineering perspective. Examines how to put together cutting-edge organizational systems that people in the financial world can put to good use. Designed to prepare students for jobs in the building, maintaining, and employment of such information systems.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/INFO/7225",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Accounting and Budgetary Systems for Engineers",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=INFO&crse_numb_in=7225",
    subject: "INFO",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=INFO&crse_in=7225&schd_in=%",
  },
  {
    classAttributes: ["Business Admin  UBBA"],
    classId: "2301",
    coreqs: { type: "and", values: [] },
    description:
      "Explores how a wide range of enterprises around the world use information and information technology to create better-managed, more innovative, and successful organizations. The twenty-first-century enterprise runs on information, and every part of the business has been transformed by the use of information technology. Today’s business leaders, therefore, must have ready access to timely, accurate, and relevant information to manage effectively in the global economy.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/MISM/2301",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Management Information Systems",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=MISM&crse_numb_in=2301",
    subject: "MISM",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=MISM&crse_in=2301&schd_in=%",
  },
  {
    classAttributes: [
      "NUpath Creative Express/Innov  NCEI",
      "NUpath Interpreting Culture  NCIC",
      "NU Core Arts Lvl 1  NCR1",
      "UG Col of Arts, Media & Design  UBAM",
    ],
    classId: "1001",
    coreqs: { type: "and", values: [] },
    description:
      "Dedicated to exploring, expanding, and exploding traditional meanings of what music is; of what it means to be a composer, performer, and audience member; and of what it means to listen. The overarching goal is to provide students with the tools and opportunities necessary for determining for themselves what place music holds in everyday life.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/MUSC/1001",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 4,
    name: "Music in Everyday Life",
    nupath: ["Creative Express/Innov", "Interpreting Culture"],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=MUSC&crse_numb_in=1001",
    subject: "MUSC",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=MUSC&crse_in=1001&schd_in=%",
  },
  {
    classAttributes: ["No Attribute information available."],
    classId: "0001",
    coreqs: { type: "and", values: [] },
    description: "Intended for administrative use only.",
    feeAmount: null,
    feeDescription: "",
    host: "neu.edu",
    id: "neu.edu/202360/NULL/0001",
    lastUpdateTime: new Date("2024-10-16T20:59:16.527Z"),
    maxCredits: 4,
    minCredits: 0,
    name: "Administrative Non-CEU",
    nupath: [],
    optPrereqsFor: [],
    prereqs: { type: "and", values: [] },
    prereqsFor: [],
    prettyUrl:
      "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_course_detail?cat_term_in=202360&subj_code_in=NULL&crse_numb_in=0001",
    subject: "NULL",
    termId: "202360",
    url: "https://wl11gp.neu.edu/udcprod8/bwckctlg.p_disp_listcrse?term_in=202360&subj_in=NULL&crse_in=0001&schd_in=%",
  },
];

export default hydrateCourseFixtures;
