#!/bin/bash
ACCOUNTID=$(aws sts get-caller-identity --query Account --output text)
TAG=$(git log -1 --pretty=%h)
REPO=$ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com/searchneu
IMG=$REPO:$TAG

aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com
docker build -t $IMG .
docker tag $IMG $REPO:staging
docker push $REPO