#!/bin/bash

function join_by { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }

if [[ ! " prod staging " =~ " $1 " ]]; then
  echo "Please provide environment to use: prod or staging"
  exit 1
fi
CLUSTER="$1-course-catalog-api"
SERVICE_WEB=$CLUSTER-webserver
TASK_WEB=$CLUSTER-webserver

# Disable aws from sending stdout to less
export AWS_PAGER=""

echo "Running one-off task on $CLUSTER cluster with command: $2"

# Get the network config from the web app service
NETCONFIG=$(aws ecs describe-services --cluster $CLUSTER --services $SERVICE_WEB --output json | jq  '.services[0].networkConfiguration' | jq '.awsvpcConfiguration.assignPublicIp = "DISABLED"')
OVERRIDES=$(printf '{"containerOverrides":[{"name":"%s","command":["%s"]}]}' "$TASK" $(join_by '","' $2))

aws ecs run-task --overrides "$OVERRIDES" --started-by "one-off task CLI" --group "one-off" --launch-type "FARGATE" --network-configuration "$NETCONFIG" --tags '[{"key": "team", "value": "searchneu"}]' --propagate-tags "TASK_DEFINITION" --task-definition $TASK_WEB --cluster $CLUSTER --output json
