name: updater

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    name: Updater
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
    env:
      TWILIO_ACCOUNT_SID: AC_dummy_value_so_tests_dont_error_out
      TWILIO_AUTH_TOKEN: 123
      UPDATE_ONLY_ONCE: true
      DATABASE_URL_WITH_CONNECTIONS: postgres://postgres.hyzilopbbumlzpkongno:H4ppVR6VirhSBPa@aws-0-us-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true&pool_timeout=0&connection_limit=15
    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
      # - run: yarn db:migrate
      # - run: yarn scrape
      - run: yarn updater
